spring:
  profiles.active: dev
---
spring:
  profiles: dev
  name: dev-YAML
  environment: dev
  logging:
    level: 
      org.hibernate: TRACE
      org.springframework.web: TRACE
      org.teco.limite: TRACE
      com.fasterxml: TRACE
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
      graylog: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  jpa:
    hibernate:
      ddl: auto=none
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: jdbc:oracle:thin:@10.76.32.76:1978:CYEDE01
    username: A000132
    password: dskore154_
    driver-class-name: oracle.jdbc.driver.OracleDriver
